{% set name = "Hypercorn" %}
{% set version = "0.5.3" %}
{% set sha256 = "97bad5887ff543e2dff0a584d1a084e702789a26df5c8fb027ac1efab32274c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - hypercorn = hypercorn.__main__:main
  skip: true  # [py < 36]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - h11 >=0.8.1
    - h2 >=3.0.1
    - pytoml >=0.1.20
    - typing_extensions >=3.6.6
    - wsproto >=0.12.0
    - uvloop >=0.11.3  # [unix]
    - trio >=0.9.0

test:
  imports:
    - hypercorn
  commands:
    - hypercorn --help

about:
  home: https://gitlab.com/pgjones/hypercorn/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A ASGI Server based on Hyper libraries and inspired by Gunicorn.'
  description: |
    Hypercorn is an ASGI web server based on the sans-io hyper, h11, h2, 
    and wsproto libraries and inspired by Gunicorn. Hypercorn supports HTTP/1, HTTP/2, 
    and websockets and the ASGI 2 specification. Hypercorn can utilise asyncio, 
    uvloop, or trio worker types.
  doc_url: https://pgjones.gitlab.io/hypercorn/
  dev_url: https://gitlab.com/pgjones/hypercorn/

extra:
  recipe-maintainers:
    - maxyme
