travis:
  secure:
    BINSTAR_TOKEN: 5Vjb2q40wXuz3j+eo1nySIJcwub0y5qYlvzbQdqnHQbBTC+OOi5fwnfbtQB+fQ5wt4RwI30Hl6QSh6Uo0apNYQN4yVAZgWAjJgkXfSh4HdnuXWzWmUuTlOYwlSPF2fFrZBfIjLLS1DMJZU874GI1c1k0c9jz50uD0dV87XtQiNGuap9OwdacQs1GqyE6gra+aWI60FHX+ZMxDrVMavTrR3KJR5DJ6/i+xDSi+t4Sp61F+axGshg0nL5fomlc8mBvQF4Mg4U6lubUsTQUlkdge9HZMP1aqgm83BIb621gO7FiIQiIeCtr398Fl2gUrh0CGkbnbaevkLavzFY0iEdCAeN79hc+RxKh+ZKKBe97YWaVAjwE3TUvIDUR59BOMFEOfD1w65gnwQcZI08kycMHYOfLKMSHa+Vko7ZhnWnEg7Gaf7Q7JI41HxM3ei1dUA09DEWgs1ml1qATJk0p0DyjEmBB+AwiaQv+2AYkg2QgwhuytMtNgGYJa1VV+S/bbFwVQ6xUHZ8INRe2AIwbEHWxQbIXbK/fUJxj4wwwJ7cwJ3/be4y9fBuYJuyhbu7aFjUTVhO4sugPFVIAztUJVvOg6LWozPfYchDoZZrnhpuJAEnVQcdNdItFoGJ2rWBcWmzeYxxFsZolzBnw82/SFAxv3EEQgx8z9sDEIZRxFJhiV44=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
